<?php

use Drupal\Core\Routing\RouteMatchInterface;

function noticias_help($route_name, RouteMatchInterface $route_match){
    switch ($route_name) {
    case 'help.page.noticias':
        return t('Esta es la información de ayuda de noticias');
    
    case 'noticias.description':
        return t('Esta es la información de ayuda del apartado de configuracion de noticias');    
    }
}

// asigna permisos como en el archivo yml
/*
function noticias_permission() {
    return array(
        'access_content' => array(
            'title' => t('Acceso a las noticias'),
            'description' => t('Permite acceder a la vista de detalle o resumen de las noticias')
        ),
        'access_config' => array(
            'title' => t('Acceso a la configuración del módulo'),
            'description' => t('Permite acceder a la configuración del módulo noticias')
        ),
    );
}*/